### PR TITLE
vp9d: fix InitDequantizer() for DRC

### PR DESCRIPTION
**Pull request by akokoshn**
-Remove VideoDECODEVP9_HW::m_*_delta_q as duplicate,
 current values already stored in m_frameInfo

### CODE REVIEW

**Comment by mgonchar** [comment]
According to your description you are not actually fixing something, but removing excessive code. Please, correct commit message

**Comment by akokoshn** [comment]
@dmitry-gurulev , agree  m_baseQIndex should be removed, but I wouldn't like mix current change with removing useless code.
I guess better do it by separate PR

**Comment by mgonchar** [comment]
@akokoshn it could be same PR but another commit. Anyway your PR should be named something like "Cleaning up vp9d excessive variables"

**Comment by akokoshn** [comment]
@mgonchar, removing m_baseQIndex not relate to issue which should be fixed by this PR.
Let's don't mix

**Comment by mgonchar** [comment]
@akokoshn do you really fixing anything? From your description I treated this commit as enhancement and refactoring. Could you describe what is the issue?

**Comment by akokoshn** [comment]
@mgonchar, this change fix corruption issue on DRC: in case of changing resolution  and quantilization coefficients decoder doesn't update  *_delta_q.
The reason updating happens if coefficients were changed ("old != new"), due to double read bit stream in case of DRC (1th read for detect resolution change). On second read  "old" values already updated (stored in m_*_delta_q), so we miss changing quantilization coefficients

**Comment by mgonchar** [comment]
ok, now the purpose of change is clear. so please put this description to your first comment, so it will appear in git history after merge of your commit

**Pull request merged**
