### PR TITLE
[h264e] Replace GetExtBuffer() to GetExtBufferRef() for MfxVideoParam

### PR DESCRIPTION
**Pull request by DenWolf**
This change fix possible problem with nullptr buffer

Signed-off-by: Denis Volkov <denis.volkov@intel.com>

### CODE REVIEW

**Comment by dmitry-gurulev** [comment]
Here is impl. of _mfxExtBufferRefProxy_ (mfx_h264_enc_common_hw.h)
```
template <typename T> operator T&()
 {
            mfxExtBuffer * p = MfxHwH264Encode::GetExtBuffer(
                m_extParam,
                m_numExtParam,
                ExtBufTypeToId<typename GetPointedType<T*>::Type>::id);
            assert(p);
            return *(reinterpret_cast<T*>(p));
 }
```
Please note that just _assert_ is used, no real pointer check in release.

**Comment by stasefremov** [comment]
Intention of GetExtBufferRef is to get ext buffers from MfxVideoParam structure which always has full set of extension buffers (so "MfxHwH264Encode::GetExtBuffer" can't return zero). Need to add respective comment near definition of the function.

**Comment by DenWolf** [comment]
@dmitryermilov , I updated commit message with clarification for this change.
Also, I created another pull request for adding clarification comment to source code:
https://github.com/Intel-Media-SDK/MediaSDK/pull/629

**Comment by DenWolf** [comment]
I tested this change on Android for h264 hw encoder - by CTS EncoderTest and screenrecord application (coded video scream from the screen of Android device using h264e) - all worked OK, tests passed.

**Pull request merged**
