### PR TITLE
[Android]Remove target libmfx_hevce_hw

### PR DESCRIPTION
**Pull request by akokoshn**
HEVCe HW was moved to libmfxhw, so remove useless target

### CODE REVIEW

**Comment by adydychk** [comment]
@akokoshn please rebase on top of master.

**Comment by adydychk** [comment]
Duplicate of #277

**Comment by akokoshn** [comment]
@adydychk , I guess need to remove this pull request

**Comment by adydychk** [comment]
Ok, I close it

**Pull request closed without merging**
