### PR TITLE
[hevce] Use VDEnc by default for A2RGB10 input

### PR DESCRIPTION
**Pull request by xhaihao**
VME doesn't support A2RGB10 input

### CODE REVIEW

**Comment by dmitryermilov** [comment]
@thomasli21801 , can you please review?

**Comment by thomasli21801** [comment]
Quick question, how about ARGB8?

**Comment by xhaihao** [comment]
Our testing shows VME supports RGB4

**Comment by thomasli21801** [comment]
> Our testing shows VME supports RGB4

Thanks Haihao, I mean from perf/quality wise or solution consolidation wise, will you prefer to direct rgb 8/10bit to VDEnc as default?

**Comment by xhaihao** [comment]
> > Our testing shows VME supports RGB4
> 
> Thanks Haihao, I mean from perf/quality wise or solution consolidation wise, will you prefer to direct rgb 8/10bit to VDEnc as default? Also, may I know which platforms this change targets?

It seems MSDK prefers VME, I don't think we need to change the default behavior.  But for rgb10bit, it is impossible to use VME.

**Comment by dmitryermilov** [comment]
> > > Our testing shows VME supports RGB4
> > 
> > 
> > Thanks Haihao, I mean from perf/quality wise or solution consolidation wise, will you prefer to direct rgb 8/10bit to VDEnc as default? Also, may I know which platforms this change targets?
> 
> It seems MSDK prefers VME, I don't think we need to change the default behavior. But for rgb10bit, it is impossible to use VME.

It's just a legacy behavior we have to keep on already released platfroms.

**Comment by thomasli21801** [comment]
got it. thanks for explanation. The change looks good to me.

**Comment by thomasli21801** [comment]
> > > Our testing shows VME supports RGB4
> > 
> > 
> > Thanks Haihao, I mean from perf/quality wise or solution consolidation wise, will you prefer to direct rgb 8/10bit to VDEnc as default? Also, may I know which platforms this change targets?
> 
> It seems MSDK prefers VME, I don't think we need to change the default behavior. But for rgb10bit, it is impossible to use VME.

This preference is for ICL and TGL, right?

**Comment by dmitryermilov** [comment]
> > > > Our testing shows VME supports RGB4
> > > 
> > > 
> > > Thanks Haihao, I mean from perf/quality wise or solution consolidation wise, will you prefer to direct rgb 8/10bit to VDEnc as default? Also, may I know which platforms this change targets?
> > 
> > 
> > It seems MSDK prefers VME, I don't think we need to change the default behavior. But for rgb10bit, it is impossible to use VME.
> 
> This preference is for ICL and TGL, right?

If a user doesn't force LowPower to some value, then AFAIR on all platforms where VME is available encoders uses VME by default.  

> Any customer is using RGB 10bit?
I don't know exactly but I assume we can build logic to prefer VME/VDEnc if user requested specific FOURCC supported only by VME/VDEnc.

**Comment by thomasli21801** [comment]
> > > > > Our testing shows VME supports RGB4
> > > > 
> > > > 
> > > > Thanks Haihao, I mean from perf/quality wise or solution consolidation wise, will you prefer to direct rgb 8/10bit to VDEnc as default? Also, may I know which platforms this change targets?
> > > 
> > > 
> > > It seems MSDK prefers VME, I don't think we need to change the default behavior. But for rgb10bit, it is impossible to use VME.
> > 
> > 
> > This preference is for ICL and TGL, right?
> 
> If a user doesn't force LowPower to some value, then AFAIR on all platforms where VME is available encoders uses VME by default.
> 
> > Any customer is using RGB 10bit?
> > I don't know exactly but I assume we can build logic to prefer VME/VDEnc if user requested specific FOURCC supported only by VME/VDEnc.

 Thanks Dmitry. I'm wondering if any exposure. The change looks good to me.

**Pull request merged**
