### PR TITLE
[Decode] Enable HEVC Upscaling

### PR DESCRIPTION
**Pull request by yawenyan**
HEVC upscaling is supported by hardware.

### CODE REVIEW

**Comment by wangyan-intel** [comment]
@yawenyan I assume this PR need driver support at first. Has the driver patch been merged?

**Comment by yawenyan** [comment]
> 

Hi Yan, driver has been  ready for upscaling.

**Comment by yawenyan** [comment]
> @yawenyan I assume this PR need driver support at first. Has the driver patch been merged?



> @yawenyan I assume this PR need driver support at first. Has the driver patch been merged?
Hi Yan, driver has been ready for upscaling.

**Pull request closed without merging**
