### PR TITLE
Change install location for plugins and samples

### PR DESCRIPTION
**Pull request by dvrogozh**

### CODE REVIEW

**Comment by dvrogozh** [comment]
@adydychk, @azhogov : CI test fails, however, this change runs successfully on my side. Question: do you run apps/plugins from the _installed_ locations or you move them elsewhere?

**Comment by azhogov** [comment]
It uses not installed location. I agree that the test scripts should be updated.

**Comment by dvrogozh** [comment]
@azhogov : this PR is supposed to address potential concerns for mediasdk system installation and packaging. Thus, this is a priority. Can you, please, give an ETA when test scripts will be updated?

**Comment by azhogov** [comment]
@dvrogozh We are going to start fix it this week. Next week the fix will be deployed.

**Comment by dvrogozh** [comment]
Ok. This PR is finally unlocked. Folks, pay attention that it will change layout of mediasdk library on the system for those who run 'make install'!!

**Comment by dvrogozh** [comment]
@onabiull : do we merge this?

**Pull request merged**
