### PR TITLE
Modify for fixing static code scan issues in CIV on WW_08 2020

### PR DESCRIPTION
**Pull request by Kexiaox**

### CODE REVIEW

**Comment by eshiryae** [comment]
@Kexiaox Could you please add all of extended structures: m_sps, m_pps, m_segPar, m_vaBrcPar, m_vaFrameRate ?

**Comment by Kexiaox** [comment]
> @Kexiaox Could you please add all of extended structures: m_sps, m_pps, m_segPar, m_vaBrcPar, m_vaFrameRate ?

Hi @eshiryae 
I have added all of extension structures, please help review

**Comment by eshiryae** [comment]
> > @Kexiaox Could you please add all of extended structures: m_sps, m_pps, m_segPar, m_vaBrcPar, m_vaFrameRate ?
> 
> Hi @eshiryae
> I have added all of extension structures, please help review

Please fix build

**Comment by dmitryermilov** [comment]
LGTM.
@eshiryae , do you approve?

**Comment by LukeZheZhu** [comment]
> Please drop copyright-only changes from this PR. And do not modify first year. 2018-2019 expected to become **2018**-2020, not **2019**-2020

Hi @onabiull 
We firstly modified the copyright only for the files changed. But buildbot reported errors and asked us to modify other file's copyright.

**Pull request merged**
