### PR TITLE
[hevce] Modify default num_ref in pps

### PR DESCRIPTION
**Pull request by perrchen**

### CODE REVIEW

**Comment by perrchen** [comment]
Addition to commits 2219/2229/2239.
After GetMaxNumRef was separated for LDB and RAB, pps L1 num_ref become always 0.
This change is to modify pps header num_ref, which help avoid some override from slice header.

**Review by lakulako — COMMENTED** [review]
Could you please improve it: set (numL0,numL1) to (P,P) if GopRefDist <= 2, (BL0,BL1) otherwise?

**Comment by dmitryermilov** [comment]
@perrchen , a recommendation: please include "Addition to commits 2219/2229/2239.
After GetMaxNumRef was separated for LDB and RAB, pps L1 num_ref become always 0.
This change is to modify pps header num_ref, which help avoid some override from slice header" into commit message so that this useful info will be seen in git log .

**Review by saosipov — APPROVED** [review]

**Review by lakulako — APPROVED** [review]

**Review by dmitryermilov — CHANGES_REQUESTED** [review]
Please squash commits

**Review by lakulako — APPROVED** [review]

**Review by dmitryermilov — APPROVED** [review]

**Pull request merged**
