### PR TITLE
[doc] Add clarification for MFX_IMPL_VIA_ANY

### PR DESCRIPTION
**Pull request by npletnev**

### CODE REVIEW

**Comment by npletnev** [comment]
@dmitryermilov, @onabiull, could you please review?

**Comment by dmitryermilov** [comment]
@npletnev, any feedbacks from your team?

**Comment by mvmaximov** [comment]
I'd also add something like "... if it's going to work with video memory (link to the corresponding section)". There is no need for the app to think of particular infrastructure if it uses system memory only.

**Comment by npletnev** [comment]
Added a few words about video memory.

**Comment by mvmaximov** [comment]
LGTM

**Comment by dmitryermilov** [comment]
@mvmaximov , add you review mark please.

**Pull request merged**
