### PR TITLE
[hevce] Expand zero ROI to minimum supported size

### PR DESCRIPTION
**Pull request by yskuridi**
Fixes [#2013](https://github.com/Intel-Media-SDK/MediaSDK/issues/2013).

Change (0 0 0 0) ROIs instead of removing them.

### CODE REVIEW

**Review by dmitryermilov — CHANGES_REQUESTED** [review]
@yskuridi , if this commit is intended to fix https://github.com/Intel-Media-SDK/MediaSDK/issues/2013, then you need to put "Fixes #2013" in commit message. 
Also, does this commit enable filling NumROI in the Query mode 2 ( from spec: _The Query function mode 2 returns maximum supported value (set it to 256 and Query will update it to maximum supported value)_)? Or it was already there?

**Comment by yskuridi** [comment]
> @yskuridi , if this commit is intended to fix #2013, then you need to put "Fixes #2013" in commit message.
Done.

> Also, does this commit enable filling NumROI in the Query mode 2 ( from spec: _The Query function mode 2 returns maximum supported value (set it to 256 and Query will update it to maximum supported value)_)? Or it was already there?
Yes, it was already there.

**Comment by dmitryermilov** [comment]
> > @yskuridi , if this commit is intended to fix #2013, then you need to put "Fixes #2013" in commit message.
> 
> Done.


I don't see an update in commit message, only in PR description .

**Comment by yskuridi** [comment]
> I don't see an update in commit message, only in PR description .

Fixed

**Review by vilichev — APPROVED** [review]

**Review by dmitryermilov — APPROVED** [review]

**Comment by dmitryermilov** [comment]
@yskuridi , just merged. Please don't forget to backport the change.

**Pull request merged**
