### PR TITLE
[sample_vpp] Remove unused code

### PR DESCRIPTION
**Pull request by AntonGrishin**
This part of MCTF code didnt work, because bAttachMctfBuffer didnt set in code below.

### CODE REVIEW

**Comment by mgonchar** [comment]
Looks ok. But I have several questions. It was added here for some purpose. What tools do we use to test MCTF (smt / transcoder)? And how hard would be to fully enable support of MCTF to this sample if we decide to do that?

**Comment by dmitryermilov** [comment]
> It was added here for some purpose. And how hard would be to fully enable support of MCTF to this sample if we decide to do that?
Yes. But the problem is the efforts apparently were not completed. Even command line parsing doesn't have per frame MCTF setting support. Now we can't finish it without understand what original idea was ... IMHO, better to remove this code.

SMT, by the way, has handling of per frame MCTF parameters.

**Comment by AntonGrishin** [comment]
@mgonchar btw, sample_vpp support MCTF 
https://github.com/Intel-Media-SDK/MediaSDK/blob/60211e10218d56e8f2e134ad5202f1da925d263e/samples/sample_vpp/src/sample_vpp_config.cpp#L96

**Comment by mgonchar** [comment]
@AntonGrishin but only with default parameters?

**Comment by AntonGrishin** [comment]
@mgonchar in block, which I provide we set params which we spicified.

**Pull request merged**
