### PR TITLE
[vp9e] Vpl branch sync 

### PR DESCRIPTION
**Pull request by IlyaSergeyev**
[VP9e] Fix input sysmem surface for vpl memory
[VP9e] Copy ScenarioInfo in case of Reset
[VP9e] Add WebRTC mode

### CODE REVIEW

**Review by alariono — APPROVED** [review]

**Review by ansokolo — APPROVED** [review]

**Review by vvbuzove — APPROVED** [review]

**Review by onabiull — CHANGES_REQUESTED** [review]
Won't this change broke opaque memory scenarios?

**Comment by vvbuzove** [comment]
> Won't this change broke opaque memory scenarios?

How could this be tested/verified?

**Comment by IlyaSergeyev** [comment]
> Won't this change broke opaque memory scenarios?

@eistarov

**Review by eistarov — APPROVED** [review]

**Comment by eistarov** [comment]
> Won't this change broke opaque memory scenarios?

Don't see any risk for opaque.

**Review by onabiull — APPROVED** [review]

**Pull request merged**
