### PR TITLE
[MCTF - ICL] Removal of excess CreateQueue calls

### PR DESCRIPTION
**Pull request by spossos**
CreateQueue(Ex) is called at init of MCTF, but later when
the kernel has been configured for operation the code had
extra CreateQueue calls, which reset the original queue,
this is an issue on ICL because ICL requires special queue
creation by using CreateQueueEx. By removing the additional
CreateQueue calls the original queue (properly configured)
is not reset and MCTF works correctly.

Issue: MDP-48160
Test: vpp_mctf_denoise

Signed-off-by: Sebastian Possos <sebastian.possos@intel.com>

### CODE REVIEW

**Comment by spossos** [comment]
Hi Oleg and Dmitry,

I am not sure why the error in windows check, as it is failing because sample_encode project has too many nested folders, but my change has nothing to do with sample_encode.

**Comment by dvrogozh** [comment]
Some patch was merged into master branch which regressed Windows build. You need to wait till it will be fixed, then just rebase your change.

**Comment by spossos** [comment]
Ohh ok, I will. Thanks!

**Comment by spossos** [comment]
I am going to push a clean new request

**Pull request closed without merging**
