### PR TITLE
Chnage the max height of VP8 decoding

### LINKED ISSUE #1215: [gstreamer-msdk][vp8 dec]not support 16x4096 resolution decoding
System Environment:
Platform: KBL/APL/SKL
Arch: x86_64
Kernel: 4.18.0+
libva commit 382acf177ce18c069e0293408afa34c5875296ff
gmmlib commit 001d32de2153e3d37f21d6dfa0a771cd3c34c9d7
msdk: commit 91eded1ef35020b85977c8fcf5d5c14645c89a37
media_driver commit [d31ce0b](https://github.com/intel/media-driver/commit/d31ce0b969733ee745e5e65316aafb66456249ae)
gstreamer master branch 5688773b91c3ea1094996a573f119230727a0978
repo: https://gitlab.freedesktop.org/gstreamer/gstreamer.git
gst-plugin-bad master branch e5278757c335f45930e1683d7068dadd49b40017
repo: https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi.git

Bug detailed description
When decode a 16x4096 resolution stream, it will decode fail

Reproduce Steps
1.build enc as above lists
2. gst-launch-1.0 -vf filesrc location=/media_stream/vp8/input_16x4096.webm ! matroskademux ! msdkvp8dec ! filesink location=./test.yuv
error info:
ERROR: from element /GstPipeline:pipeline0/GstMsdkVP8Dec:msdkvp8dec0: Could not negotiate the stream
Additional debug info:
gstmsdkdec.c(968): gst_msdkdec_handle_frame (): /GstPipeline:pipeline0/GstMsdkVP8Dec:msdkvp8dec0
ERROR: pipeline doesn't want to preroll.
3. use sample_decode to decode this case, also fail
sample_decode vp8 -i /media_stream/vp8/input_16x4096.ivf -o test.yuv
error info:
[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), Init, m_FileReader->Init failed at /root/build/MediaSDK/samples/sample_decode/src/pipeline_decode.cpp:227

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), main, Pipeline.Init failed at /root/build/MediaSDK/samples/sample_decode/src/sample_decode.cpp:666

### PR DESCRIPTION
**Pull request by wangyan42164**
Fixes #1215.

Signed-off-by: Yan Wang <yan.wang@linux.intel.com>

### CODE REVIEW

**Comment by dvrogozh** [comment]
@wangyan42164 : please, rebase to fetch ci fix merged into master.

**Comment by wangyan42164** [comment]
@dvrogozh I have rebased this PR. Let's wait CI build finished. Thanks.

**Comment by guowillyy** [comment]
chnage -> change

**Comment by wangyan42164** [comment]
> chnage -> change

I have changed it. Thanks.

**Review by guowillyy — APPROVED** [review]

**Review by wangyan-intel — APPROVED** [review]

**Review by dvrogozh — APPROVED** [review]
Complies with https://github.com/intel/media-driver/blob/master/docs/media_features.md#supported-decoding-output-format-and-max-resolution. Hence, LGTM.

**Review by onabiull — APPROVED** [review]

**Pull request merged**
