### PR TITLE
[vpp] Support P010 output

### PR DESCRIPTION
**Pull request by mvafin**

### CODE REVIEW

**Comment by rkazants** [comment]
Did you check that it works for resize?

**Comment by mvafin** [comment]
Yes, I did check it. It works for resize.

**Comment by ishmael1985** [comment]
Will this feature ever be merged to master? This looks useful when performing 10-bit HEVC encode of original 8-bit samples.

**Comment by dvrogozh** [comment]
Considering that this PR is closed, it has low chance to be merged:). @mvafin : why this work was not finished?

**Comment by ishmael1985** [comment]
Any hope that this feature request will be re-opened sometime later? Would VPP P010 output be supported by KBL onwards?

**Comment by dvrogozh** [comment]
@mvafin : so, do we support this feature now or not? for which platforms?

**Comment by mvafin** [comment]
@dvrogozh : yes, we do support this feature. It is supported starting from CFL, so on KBL it shouldn't work.

**Comment by ishmael1985** [comment]
So it already works now from CFL onwards?

**Comment by mvafin** [comment]
@ishmael1985, yes

**Comment by ishmael1985** [comment]
@mvafin thanks a lot for the info. It's a bit sad that P010 VPP output works on Windows from KBL onwards, and for Linux it's from CFL onwards. Weirdly, HEVC 10-bit encode works on KBL for open-source (and Windows) MSDK, but the media driver states in the README that only CNL onwards can support HEVC 10-bit encode. Holding out for a bit of hope I guess...

**Comment by ishmael1985** [comment]
@dvrogozh @mvafin seems like it NV12 -> P010 is working now for KBL with the latest msdk and media-driver master.

**Pull request closed without merging**
