### PR TITLE
trace: remove duplicate code

### PR DESCRIPTION
**Pull request by guoyejun**

### CODE REVIEW

**Comment by dvrogozh** [comment]
fix copyright year to unlock CI, please.

**Comment by guoyejun** [comment]
sorry, does this mean that i need to close this PR and then open a new one?

I merged the two changes into one locally, but unable to push it into the same branch.  I think a new PR will be raised if I use a new branch name. 

Is it right? thanks.

**Comment by guoyejun** [comment]
created https://github.com/Intel-Media-SDK/MediaSDK/pull/1795 and close this one.

**Comment by dvrogozh** [comment]
> does this mean that i need to close this PR and then open a new one?

no. you can push with the force next time: `git push --force origin HEAD:refs/heads/<branch>`

**Pull request closed without merging**
