### PR TITLE
fixing path for samples

### PR DESCRIPTION
**Pull request by maximd33**

### CODE REVIEW

**Comment by amaslenn** [comment]
Have you checked it with Cmake 2.8?

**Comment by maximd33** [comment]
using Ubuntu latest
```
cmake --version
cmake version 3.5.2
```

**Comment by amaslenn** [comment]
With your changes and 
```sh
$ cmake --version
cmake version 2.8.11
```
I get following error:
```sh
I am going to execute:
  cmake --no-warn-unused-cli -Wno-dev -G "Unix Makefiles" -D__GENERATOR:STRING=make -DCMAKE_CONFIGURATION_TYPES:STRING="release;debug" -DCMAKE_BUILD_TYPE:STRING=release -D__ARCH:STRING=intel64 -D__CONFIG:STRING=release -D__IPP:STRING=e9 -D__TARGET_PLATFORM:STRING=BDW -DWARNING_FLAGS="-Wall -Werror" /msdk/0_work/open-source/MediaSDK
[ cmd ]: cmake --no-warn-unused-cli -Wno-dev -G "Unix Makefiles" -D__GENERATOR:STRING=make -DCMAKE_CONFIGURATION_TYPES:STRING="release;debug" -DCMAKE_BUILD_TYPE:STRING=release -D__ARCH:STRING=intel64 -D__CONFIG:STRING=release -D__IPP:STRING=e9 -D__TARGET_PLATFORM:STRING=BDW -DWARNING_FLAGS="-Wall -Werror" /msdk/0_work/open-source/MediaSDK
Not searching for unused variables given on the command line.
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- OpenCL was found here: /opt/intel/opencl and /opt/intel/opencl/include
-- CMAKE_INSTALL_PREFIX=/opt/intel/mediasdk
fatal: No annotated tags can describe 'e7dc343fe945cf1ebde2ba772b8e6838712b4a18'.
However, there were unannotated tags: try --tags.
-- Intel(R) Media SDK was found here /msdk/0_work/open-source/MediaSDK
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1")
-- checking for module 'libva>=0.33'
--   found libva, version 0.99.0
-- checking for module 'libdrm'
--   found libdrm, version 2.4.66
--   found libva-drm, version 0.99.0
-- checking for module 'x11'
--   found x11, version 1.6.3
-- checking for module 'libva-x11>=0.33'
--   found libva-x11, version 0.99.0
-- Global Configuration of Targets
-- Target Architecture to compile: sse4.2
fatal: No annotated tags can describe 'e7dc343fe945cf1ebde2ba772b8e6838712b4a18'.
However, there were unannotated tags: try --tags.
fatal: No annotated tags can describe 'e7dc343fe945cf1ebde2ba772b8e6838712b4a18'.
However, there were unannotated tags: try --tags.
fatal: No annotated tags can describe 'e7dc343fe945cf1ebde2ba772b8e6838712b4a18'.
However, there were unannotated tags: try --tags.
fatal: No annotated tags can describe 'e7dc343fe945cf1ebde2ba772b8e6838712b4a18'.
However, there were unannotated tags: try --tags.
-- OpenCL was found here: /opt/intel/opencl and /opt/intel/opencl/include
Error copying file "/msdk/0_work/open-source/MediaSDK/samples/samples/sample_plugins/rotate_opencl/src/ocl_rotate.cl" to "/msdk/0_work/open-source/MediaSDK/__cmake/intel64.make.release/__bin/release/ocl_rotate.cl".
-- Configuring done
CMake Error at lib/builder/FindFunctions.cmake:189 (add_library):
  Cannot find source file:

    /msdk/0_work/open-source/MediaSDK/samples/samples/sample_plugins/plugins_common_files/mfx_plugin_module.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  samples/sample_plugins/rotate_cpu/CMakeLists.txt:14 (make_library)


-- Build files have been written to: /msdk/0_work/open-source/MediaSDK/__cmake/intel64.make.release
```

**Comment by amaslenn** [comment]
Issue with `Cmake >= 3.0` will be addressed.

**Pull request closed without merging**
