### PR TITLE
[Dispatcher] Add cmake files for Windows platform

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by wangyan-intel** [comment]
Thanks for your contribution. In general, this repo is for Linux only. It doesn't include MSDK windows runtime.

**Comment by Biswa96** [comment]
The dispatcher library only has Visual Studio project files. With CMake, one can compile or cross compile it without Visual Studio. It will not require MS c/c++ runtime and will link with any other c/c++ libraries that comes with compiler toolchain e.g. gcc, clang etc.

**Comment by wangyan-intel** [comment]
So you just need compile dispatcher for Windows? Windows Intel media driver folder should include MSDK built runtime and dispatcher which are close source.

**Comment by Biswa96** [comment]
> So you just need compile dispatcher for Windows?

Yes.

**Comment by wangyan-intel** [comment]
This repo is not used to accept the patch for Windows code.

**Comment by Biswa96** [comment]
CMake project was also requested here https://github.com/Intel-Media-SDK/MediaSDK/issues/2935

**Pull request closed without merging**
