### PR TITLE
Add platform restriction

### PR DESCRIPTION
**Pull request by kchen1024**

### CODE REVIEW

**Comment by lwan108** [comment]
@kchen1024, could you please share some background for this change?

**Comment by kchen1024** [comment]
> @kchen1024, could you please share some background for this change?

Sure. Previous change (https://github.com/Intel-Media-SDK/MediaSDK/pull/2951/files) added interlaced setting to surface. However regression for interfaced FRC cases occur for ICL before platform due to hw not supported. Therefore disable these setting for ICL before platform.

**Comment by lwan108** [comment]
> > @kchen1024, could you please share some background for this change?
> 
> Sure. Previous change (https://github.com/Intel-Media-SDK/MediaSDK/pull/2951/files) added interlaced setting to surface. However regression for interfaced FRC cases occur for ICL before platform due to hw not supported. Therefore disable these setting for ICL before platform.

Thanks, looks good to me.

**Review by lwan108 — DISMISSED** [review]

**Review by MicroYY — APPROVED** [review]

**Comment by kchen1024** [comment]
Ubuntu-20.04 / gcc11 (pull_request) failure is due to env issue.

**Pull request merged**
