### PR TITLE
[MCTF/ASC] CMC update for all kernels and general cleanup

### PR DESCRIPTION
**Pull request by spossos**
Migration of Cm kernel compilation from icl to cmc for
all platforms, addition of compiled kernel for ICL and
ICLLP (Gen11).
Fixed issues related to low power platforms (BXT, GLK, ICLLP)
based on constants being interpreted by compiler as doubles
which are not supported on those platforms.
General cleanup of MCTF code, removal of MFX_ENABLE_MCTF_EXT
definition from MCTF and sample_vpp code as mctf extended
features are not approved until further notice.
Removal of deprecated feature MRE and cleanup.

Issue: -
Test: Manual test

### CODE REVIEW

**Comment by onabiull** [comment]
Please rebase. CI was restored, so we'll see this PR status.

**Comment by spossos** [comment]
Very well, I will do

**Comment by spossos** [comment]
My plan is when this pull is merged I will work on ASC - MFX_ENABLE_KERNELS, is that ok?

**Comment by onabiull** [comment]
Please rebase once more time. And previous rebase was a bit strange, please make sure that we would be able to create linear history, i.e. no merges.

**Pull request merged**
