### PR TITLE
[Decode]Enable AVC CSC via sfc pipeline

### PR DESCRIPTION
**Pull request by shawnli2**
AVC SFC CSC is supported

### CODE REVIEW

**Review by dmitryermilov — COMMENTED** [review]
@shawnli2 , are there any HW limitations for CSC?

**Comment by shawnli2** [comment]
> @shawnli2 , are there any HW limitations for CSC?
I 
@dmitryermilov  Yes, platform before TGL only support 8 bit output format, UpdateCscOutputFormat() will query and check. If do not support, will return MFX_ERR_INVALID_VIDEO_PARAM.

**Comment by dmitryermilov** [comment]
> > @shawnli2 , are there any HW limitations for CSC?
> > I
> > @dmitryermilov  Yes, platform before TGL only support 8 bit output format, UpdateCscOutputFormat() will query and check. If do not support, will return MFX_ERR_INVALID_VIDEO_PARAM.
> > https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/mfx_lib/shared/src/mfx_common_int.cpp#L305

Thanks. But MFX_ERR_INVALID_VIDEO_PARAM seems to be incorrect status. Can you please change it to MFX_ERR_UNSUPPORTED in another PR?

**Review by dmitryermilov — APPROVED** [review]

**Comment by shawnli2** [comment]
> > > @shawnli2 , are there any HW limitations for CSC?
> > > I
> > > @dmitryermilov  Yes, platform before TGL only support 8 bit output format, UpdateCscOutputFormat() will query and check. If do not support, will return MFX_ERR_INVALID_VIDEO_PARAM.
> > > https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/mfx_lib/shared/src/mfx_common_int.cpp#L305
> 
> Thanks. But MFX_ERR_INVALID_VIDEO_PARAM seems to be incorrect status. Can you please change it to MFX_ERR_UNSUPPORTED in another PR?

Thanks for review. Sure, I will!

**Pull request merged**
