### PR TITLE
[IMPORTANT] Discontinuation of Media SDK Project

### PR DESCRIPTION
**Pull request by daleksan**

### CODE REVIEW

**Review by mgonchar — DISMISSED** [review]
Farewell MSDK

**Comment by dvrogozh** [comment]
@ community : if there is an interest in community to create centralized fork of original msdk git repository and continue bug fix effort, please, react to this comment of mine.

**Review by yefeizhou — DISMISSED** [review]
Farewell MSDK

**Comment by dmitryermilov** [comment]
RIP

**Comment by daleksan** [comment]
@ community please provide your questions in the announcement, posted in the discussion tab: https://github.com/Intel-Media-SDK/MediaSDK/discussions/3037

**Pull request merged**
