### PR TITLE
Fixes 'invalid use of non-static data member' error on clang 6.0

### PR DESCRIPTION
**Pull request by IlyaSergeyev**

### CODE REVIEW

**Comment by dvrogozh** [comment]
Why no CI build checks were ran? This change breaks build against gcc-8.1 with:
`MediaSDK/tools/bs_parser_hevc/include/bs_mem+.h:56:19: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct BS_HEVC2::TU’; use assignment or value-initialization instead [-Werror=class-memaccess]
`

**Comment by mgonchar** [comment]
@dvrogozh  this patch changed code which has no relation to bs_parser.

Bs_parser just missing some changes which were made in same code for parser in sample_hevc_fei_abr (that sample has it's own copy of bs_parser and code between those two somehow misaligned)

**Comment by dvrogozh** [comment]
Yeah... Oleg noted to me that this change could not introduce this issue and instead we had misconfigured CI which tested something else rather than gcc-8.1... Well, bad things happen. But now we have a blocker issue.

**Comment by GoAlexander** [comment]
We used gcc 7 instead of gcc 8... But now it is fixed.

**Pull request merged**
