### PR TITLE
Add dispatcher for UWP apps

### PR DESCRIPTION
**Pull request by npletnev**

### CODE REVIEW

**Comment by npletnev** [comment]
@dmitryermilov Most of the VS projects are included in AllBuild.sln and have separate solutions, so I made the same here. Or should we remove all the separate solutions?

**Comment by dmitryermilov** [comment]
> @dmitryermilov Most of the VS projects are included in AllBuild.sln and have separate solutions, so I made the same here. Or should we remove all the separate solutions?

Only samples have them. Tools and tutorials don't have. Please remove.

**Comment by dvrogozh** [comment]
Anything we put into repository should be supported (optimally at least:)). In our CI we validate only top level AlllBuild.sln. So, any other solution will be off the radar at some point. I really considering that we should drop individual samples solutions as well for this reason - I am just lazy enough to do that.

Or we will finally switch to cmake across board at some point and drop everything:).

**Comment by onabiull** [comment]
Cmake is closer, than you may think :). So from my perspective number of sln files doesn't matter that much. They going to be phased out soon.

**Comment by dvrogozh** [comment]
I'll be on skeptical side. So: any new solutions not covered by CI should not be allowed in. Will be easier to clean up later...

**Comment by dmitryermilov** [comment]
@npletnev , please address concerns or remove the PR.

**Pull request merged**
