### PR TITLE
Fixes for av1d film grain on Linux

### PR DESCRIPTION
**Pull request by wangyan42164**

### CODE REVIEW

**Review by dmitryermilov — APPROVED** [review]

**Review by onabiull — APPROVED** [review]

**Comment by wangyan42164** [comment]
@dmitryermilov @onabiull I find CI build isn't started. Now I have rebased this PR but it seems not to start CI builds still. Could you please help take a look? Thanks.

**Comment by onabiull** [comment]
@eponomar, please take a look?

**Comment by eponomar** [comment]
All revisions does exist in Buildbot CI DB, but build request creation was failed because HTTP 502 error for last 2 revisions.
@wangyan42164 , could you please re-push changes?

**Comment by wangyan42164** [comment]
> All revisions does exist in Buildbot CI DB, but build request creation was failed because HTTP 502 error for last 2 revisions.
> @wangyan42164 , could you please re-push changes?

@eponomar I will try

**Comment by wangyan42164** [comment]
@eponomar I have re-push the last 2 commits. If it still cannot work, I can submit them in another PR.

**Comment by wangyan42164** [comment]
@onabiull @dmitryermilov Now CI build has passed. Could you please review it again? Thanks.

**Review by dmitryermilov — APPROVED** [review]

**Pull request merged**
