### PR TITLE
Fixed check max DPB size and NumRefFrame for HEVCe

### PR DESCRIPTION
**Pull request by iveselov**

### CODE REVIEW

**Comment by lakulako** [comment]
Alternative is https://github.com/Intel-Media-SDK/MediaSDK/pull/652

**Comment by lakulako** [comment]
In this patch maxDPB is reduced so that NumRefFrame was <=. While DBP contains reference frames + current frame it seems to be better to limit NumRefFrame directly to <= maxDPB-1. What is done in #652.

**Comment by iveselov** [comment]
MAX_DPB_SIZE for encoder is already set, considering current frame. I think, it is less readable to set maxDPB magic number, which can't be achived

**Comment by lakulako** [comment]
maxDPB is already computed and verified according to DPB described in spec. It includes reference frames and current frame. It is apparent to require maxNumRefFrame == maxDPB-1.
maxDPB was 16 and it would be incorrect to reduce it.
MAX_DPB_SIZE is our internal variable that represents size of array with reference frames. It is more magic and dangerous to use defines that have similar roots in name but different sense.
More accurate would be to rename MAX_DPB_SIZE to something like MAX_REF_FRAMES to avoid confuses.

**Comment by onabiull** [comment]
Alternative version merged.

**Pull request closed without merging**
